stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t badcapt -f badcapt-tg.Dockerfile .

deploy:
  stage: deploy
  script:
    - docker stop badcapt
    - docker rm badcapt
    - docker run -d --net=host --name=badcapt --restart=always -e API_KEY=${API_KEY} badcapt -i eth0 -chat=${CHAT_ID}
