stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t badcapt -f badcapt-nats.Dockerfile .

deploy:
  stage: deploy
  script:
    - docker stop badcapt
    - docker rm badcapt
    - docker run -d --net=host --name=badcapt --restart=always -e CLIENT_ID=$CLIENT_ID -e NATS_URL=$NATS_URL badcapt -i eth0
