language: go

go:
  - master

services:
  - docker

env:
  global:
    - GO111MODULE=on GOOS=linux GOARCH=amd64

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev

script:
  - go build ./...
  - docker build -t badcapt .

before_deploy:
  - go build -ldflags="-s -w" -a -installsuffix static -o badcapt-${TRAVIS_TAG} cmd/badcapt/badcapt.go

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  skip_cleanup: true
  file:
    - badcapt-${TRAVIS_TAG}
  on:
    repo: ilyaglow/badcapt
    tags: true
